-- assignment 2

use sakila;

-- Question 1: Retrieve the total number of rentals made in the Sakila database. 

select * from rental;

select count(rental_id) from rental;

-- Question 2: Find the average rental duration (in days) of movies rented from the Sakila database

select * from film;

select avg(rental_duration) from film; 

-- Question 3: Display the first name and last name of customers in uppercase. 

select upper(first_name),upper(last_name) from customer;

use mavenmovies;

-- Question 4:  Extract the month from the rental date and display it alongside the rental ID. 

select month(rental_date),rental_id from rental;

-- Question 5:Retrieve the count of rentals for each customer (display customer ID and the count of rentals). 

select * from payment;

select customer_id,count(rental_id) from payment group by customer_id; 

-- Question 6: Find the total revenue generated by each store. 

select * from store;

select s.store_id,sum(p.amount) as total_revenue from store s join staff sf on s.store_id=sf.store_id 
join payment p on sf.staff_id=p.staff_id group by s.store_id;

-- Question 7: Display the title of the movie, customer  first name, and last name who rented it. 

select f.title,c.first_name,c.last_name from film f join inventory i on f.film_id=i.film_id 
join rental r on i.inventory_id=r.inventory_id join customer c on r.customer_id=c.customer_id;

-- Question 8:  Retrieve the names of all actors who have appeared in the film "Gone with the Wind." 

select  f.title,a.first_name,a.last_name from actor a join film_actor fa on a.actor_id=fa.actor_id join 
film f on fa.film_id=f.film_id where f.title='Gone with the wind';

-- GROUP BY: 

-- Question 1:  Determine the total number of rentals for each category of movies. 

select * from film_category;

select c.category_id,count(r.rental_id) from rental r join inventory i on r.inventory_id=i.inventory_id
join film f on i.film_id=f.film_id join film_category c on f.film_id=c.film_id group by c.category_id;

-- Question 2:  Find the average rental rate of movies in each language. 

select * from film;

select l.name, avg(f.rental_rate) from film f right join language l on f.language_id=l.language_id
group by l.name;

-- Question 3:  Retrieve the customer names along with the total amount they've spent on rentals. 

select c.customer_id,c.first_name,c.last_name,sum(p.amount) from customer c join payment p on c.customer_id=p.customer_id
join rental r on c.customer_id=r.customer_id group by c.customer_id;

-- Question 4:  List the titles of movies rented by each customer in a particular city (e.g., 'London'). 

select c.first_name,c.last_name,f.title,ct.city from customer c join address a on c.address_id=a.address_id
join city ct on a.city_id=ct.city_id join rental r on c.customer_id=r.customer_id join
inventory i on r.inventory_id=i.inventory_id join film f on i.film_id=f.film_id
where ct.city='london' order by c.first_name,c.last_name,f.title;

-- Question 5:Display the top 5 rented movies along with the number of times they've been rented.

select f.title,count(*) from  film f join inventory i on f.film_id=i.film_id join rental r on
i.inventory_id=r.inventory_id group by f.title limit 5;

-- Question 6:  Determine the customers who have rented movies from both stores (store ID 1 and store ID 2). 

select c.first_name,c.last_name,s.store_id from customer c join rental r on c.customer_id=r.customer_id
join inventory i on r.inventory_id=i.inventory_id join store s on i.store_id=s.store_id
where s.store_id in(1,2) group by c.customer_id;